name: 'Get apt package version'
description: 'This action gets the version of a package in an Ubuntu/Debian APT repository'
inputs:
  baseImage:
    description: "Ubuntu/Debian based image to use"
    required: true
    default: "debian:bookworm"
  package:
    description: "Package to look for"
    required: true
  ppa:
    description: "Additional PPA repository"
    required: false
outputs:
  version:
    description: "The version of the package"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.baseImage }}
    - ${{ inputs.ppa && '-p' }}
    - ${{ inputs.ppa }}
    - ${{ inputs.package }}