name: Check Dependencies

on:
  #schedule:
  #  - cron: '45 * * * *'
  workflow_dispatch:

jobs:
  get-config:
    runs-on: ubuntu-latest
    outputs:
      debian_version: ${{ steps.config.outputs.debian_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run YAML to Github Output Action
        id: config
        uses: christian-ci/action-yaml-github-output@v2
        with:
          file_path: config.yaml

  get-deps:
    runs-on: ubuntu-latest
    needs: get-config
    outputs:
      test-libcamera0_version: ${{ steps.libcamera0_version.outputs.version }}
    strategy:
      matrix:
        debian_version: ${{fromJson(needs.get-config.outputs.debian_version)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lookup libcamera0 version
        id: libcamera0_version
        uses: OctoPrint/actions/latest-apt-version@main
        with:
          package: libcamera0
          url: https://archive.raspberrypi.org/debian/dists/${{ matrix.debian_version }}/main/binary-armhf/Packages

      - name: Output libcamera0 version
        run: |
          echo libcamera0_version: ${{ steps.libcamera0_version.outputs.version }}

  check-results:
    runs-on: ubuntu-latest
    needs: get-deps
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Check get-deps results
        run: |
          echo libcamera0_version: ${{ needs.get-deps.outputs.libcamera0_version }}