name: Check Dependencies

on:
  #schedule:
  #  - cron: '45 * * * *'
  workflow_dispatch:

jobs:
  get-config:
    runs-on: ubuntu-latest
    outputs:
      libcamera0_bullseye_armhf: ${{ steps.config.outputs.libcamera0_bullseye_armhf }}
      libcamera0_bullseye_arm64: ${{ steps.config.outputs.libcamera0_bullseye_arm64 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run YAML to Github Output Action
        id: config
        uses: christian-ci/action-yaml-github-output@v2
        with:
          file_path: config.yaml

  check-libcamera-bullseye32:
    runs-on: ubuntu-latest
    needs: get-config
    steps:
      - name: Lookup libcamera0 version
        id: libcamera0_version
        uses: OctoPrint/actions/latest-apt-version@main
        with:
          package: libcamera0
          url: https://archive.raspberrypi.org/debian/dists/bullseye/main/binary-armhf/Packages

      - name: Lookup libcamera0 version
        id: libcamera0_version2
        uses: OctoPrint/actions/latest-apt-version@main
        with:
          package: libcamera0
          url: https://archive.raspberrypi.org/debian/dists/bullseye/main/binary-arm64/Packages

      - name: Lookup libcamera0 version
        id: libcamera0_version3
        uses: OctoPrint/actions/latest-apt-version@main
        with:
          package: libcamera0
          url: https://archive.raspberrypi.org/debian/dists/bookworm/main/binary-arm64/Packages

      - name: Output libcamera0 version
        run: |
          echo libcamera0_version: ${{ steps.libcamera0_version.outputs.version }}